version: '2'

services:
  db:
    image: postgres
  web:
    build: .
    command: ./run_server.sh
    environment:
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db